// Generated by CoffeeScript 1.6.3
var $dataTable, action, add, aromas, blnd, getField, init, remove, setField, update, updateDOM;

aromas = [];

blnd = null;

$dataTable = void 0;

init = function() {
  $dataTable = $('#blender-data');
  blnd = new Blender();
  return updateDOM();
};

add = function(e) {
  var $aroma, $aromas, aroma, aromaID, aromaName, aromaValue, html;
  e.preventDefault();
  aromaName = $('input-aromaname').val();
  aromaValue = $('input-aromavalue').val();
  $aromas = $('.aromas');
  aromaID = aromas.length < 1 ? 0 : aromas.length;
  aroma = blnd.addAroma("aroma-" + aromaID, "Aroma " + aromaID, 0);
  aromas.push(aroma);
  html = "<div class=\"form-group\" id=\"" + aroma.id + "\">            <div class=\"col-sm-2\">                <input type=\"text\" class=\"form-control control-label\" id=\"input-" + aroma.id + "-name\" placeholder=\"Aroma " + aromaID + "\">            </div>            <div class=\"col-sm-1\">                <input type=\"text\" class=\"form-control\" id=\"input-" + aroma.id + "\" value=\"" + aroma.value + "\">            </div>            <div class=\"col-sm-1\">                <p class=\"form-control-static\">%</p>            </div>            <div class=\"col-sm-5\">                <button tabindex=\"-1\" class=\"btn btn-danger btn-sm\"><span class=\"glyphicon glyphicon-remove\" style=\"vertical-align: -1px\"></span></button>            </div>        </div>";
  $aromas.append(html);
  $aroma = $("#" + aroma.id);
  $aroma.find('button').on('click', remove);
  return $aroma.find("input").on('blur', update);
};

remove = function(e) {
  var elm, elmID;
  e.preventDefault();
  elm = $(e.target).parents('.form-group');
  elmID = parseInt(elm.attr('id').replace('aroma-', ''));
  aromas.splice(parseInt(elmID), 1);
  blnd.removeAroma(elm.attr('id'));
  updateDOM();
  $("#recipe-" + (elm.attr('id'))).remove();
  return elm.remove();
};

update = function(e) {
  var $elm, id, val, _IDtokens;
  e.preventDefault();
  $elm = $(e.target);
  id = $elm.attr('id').replace('input-', '');
  val = $elm.val();
  _IDtokens = id.split('-');
  if (_IDtokens[2]) {
    blnd.setAroma(id.replace('-name', ''), {
      name: val
    });
  } else if (_IDtokens[0] === 'aroma') {
    blnd.setAroma(id, {
      value: parseInt(val)
    });
  } else {
    blnd[id] = parseInt(val);
  }
  updateDOM();
  return console.log(blnd);
};

action = function(actionName) {
  return $("[data-action=\"" + actionName + "\"]");
};

getField = function(id, fieldName) {
  return $("#recipe-" + id).find("[data-field=\"" + fieldName + "\"]");
};

setField = function(id, data) {
  var field, value;
  for (field in data) {
    value = data[field];
    getField(id, field).text(value);
  }
};

updateDOM = function() {
  var html;
  html = "";
  $.each(blnd.getIngredients(), function(i, v) {
    html += "<tr id=\"recipe-" + i + "\">";
    html += "<th data-field=\"name\">" + v.name + "</th>";
    html += "<td data-field=\"drops\">" + v.drops + "</td>";
    html += "<td data-field=\"liquidAmount\">" + v.value + "</td>";
    html += "<td data-field=\"percentage\">" + v.percentage + "</td>";
    return html += "</tr>";
  });
  return $dataTable.find('tbody').html(html);
};

$(function() {
  init();
  action('update').on('blur', update);
  return action('add').on('click', add);
});
