// Generated by CoffeeScript 1.6.3
var Recipe;

Recipe = (function() {
  function Recipe() {
    this.liquidAmount = 10;
    this.dropsPrMl = 25;
    this.pg = 50;
    this.vg = 50;
    this.nicoPGVG = 32;
    this.nicoTarget = 16;
    this.water = 0;
    this.Aromas = {};
    update();
  }

  Recipe.prototype.addAroma = function(id, name, value) {
    this.Aromas[id] = {
      name: name,
      value: value
    };
    return update();
  };

  Recipe.prototype.removeAroma = function(id) {
    return delete this.Aromas[id];
  };

  Recipe.prototype.setValueForAroma = function(id, value) {
    this.Aromas[id].value = value;
    return update();
  };

  Recipe.prototype.update = function() {
    var add, aroma, total, _i, _len, _ref;
    this.nicoPGVG = (this.nicoPGVG <= 0 ? 0 : 100 * this.nicoTarget / this.nicoPGVG);
    total = 0;
    add = function(i) {
      return total += parseInt(i.value);
    };
    if (typeof this.Aromas === 'object') {
      _ref = this.Aromas;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        aroma = _ref[_i];
        add(aroma);
      }
    }
    this.pg = this.pg - ((this.nicoPGVG / 2) + ((this.water + total) * (this.pg / 100)));
    return this.vg = this.vg - ((this.nicoPGVG / 2) + ((this.water + total) * (this.vg / 100)));
  };

  return Recipe;

})();
